### ISSUE TITLE
ImportError with Plone 5.1.6 and Python 2.7.13

### ISSUE THREAD

**Issue by spanish** [collective/collective.portlet.tal#2]
Any idea? Thanks

$ bin/client1 fg
    ...
    ZopeXMLConfigurationError: File "/home/plone/51/buildout-cache/eggs/Products.CMFPlone-5.1.6-py2.7.egg/Products/CMFPlone/configure.zcml", line 105.2-109.8
    ZopeXMLConfigurationError: File "/home/plone/51/buildout-cache/eggs/collective.portlet.tal-1.2.0-py2.7.egg/collective/portlet/tal/configure.zcml", line 27.5-36.11
    ImportError: No module named formlib

**Comment by espenmn** [comment]
Is fixed in code, will be in version 1.2.1

**Comment by espenmn** [comment]
Fixed in version 1.2.1
